name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python: ["3.9"]

    steps:
      - uses: compas-dev/compas-actions.build@v4
        with:
          python: ${{ matrix.python }}
          invoke_lint: true
          invoke_test: true

  Publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions.publish@v3
        with:
          pypi_token: ${{ secrets.PYPI }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
